#!/bin/bash




function get_slm_ip {
   export SLM_IP=`ping -c1 -n $SLM_NAME  | head -n1 | sed "s/.*(\([0-9]*\.[0-9]*\.[0-9]*\.[0-9]*\)).*/\1/g" `
 }



echo "$@"  >> $OPENSHIFT_MARIADB_DIR/slm-hook-log
echo "$@"  >  $OPENSHIFT_MARIADB_DIR/slm-hook-log-latest


SLM_NAME=`cat slm-hook-log-latest | sed "s/'//g" | grep -m 1 -o 'OPENSHIFT_FROM_SLM_NODE=.*' | cut -d '=' -f 2 | cut -d ':' -f 1`
SLM_PORT=`cat slm-hook-log-latest | sed "s/'//g" | grep -m 1 -o 'OPENSHIFT_FROM_SLM_NODE=.*' | cut -d '=' -f 2 | cut -d ':' -f 2`

get_slm_ip


if [ "$SLM_NAME" ]
then

#SL has joined
#set the SLM registry file

sed -e "s|OPENSHIFT_MARIADB_DB_HOST|`printf "%-20s" ${SLM_IP}`|" ${OPENSHIFT_MARIADB_DIR}/bin/slm.registry.tmp > ${OPENSHIFT_MARIADB_DIR}/slm.registry.tmp2
    

sed -e "s|OPENSHIFT_MARIADB_SLM_PROXY_PORT|`printf "%-7s" ${SLM_PORT}`|" ${OPENSHIFT_MARIADB_DIR}/slm.registry.tmp2 > /tmp/data/slm.registry


#start the CAS


export running=`pgrep scaledb_cas`

echo $running > t92

if [ -z "$running" ]
then
echo "CAS not running" + $running
  
  ${OPENSHIFT_MARIADB_DIR}/michael44/scaledb-latest-mariadb-5.5.34/lib/scaledb_cas ${OPENSHIFT_MARIADB_DIR}/cas.cnf $OPENSHIFT_MARIADB_DB_HOST $OPENSHIFT_MARIADB_CAS_PORT  > t1.txt 2>&1 &

fi



fi
