#!/bin/bash




function get_cas_ip {
   export CAS_IP=`ping -c1 -n $CAS_NAME  | head -n1 | sed "s/.*(\([0-9]*\.[0-9]*\.[0-9]*\.[0-9]*\)).*/\1/g" `
 }


#set -e

# Manual Test
# sh hooks/set-mariadb-node publish-mariadb mariadb andrewklau GEAR-DNS:MYSQL-PORT:GALERA-PORT:SST-PORT

#app_name=$1
#namespace=$2
#local_gear=$3

echo $1 > $OPENSHIFT_MARIADB_DIR/hook-log1
echo $2 > $OPENSHIFT_MARIADB_DIR/hook-log2
echo $3 > $OPENSHIFT_MARIADB_DIR/hook-log3
echo $4 > $OPENSHIFT_MARIADB_DIR/hook-log4

echo "$@"  >> $OPENSHIFT_MARIADB_DIR/hook-log
echo "$@"  >  $OPENSHIFT_MARIADB_DIR/hook-log-latest

#CAS_NAME=`cat hook-log-latest | sed "s/'//g" | grep -m 1 -o 'OPENSHIFT_CAS_NODE_FROM_STORAGE=.*' | cut -d '=' -f 2 | cut -d ':' -f 1`
#CAS_PORT=`cat hook-log-latest | sed "s/'//g" | grep -m 1 -o 'OPENSHIFT_CAS_NODE_FROM_STORAGE=.*' | cut -d '=' -f 2 | cut -d ':' -f 2`

#get the scond address
CAS_NAME_ARRAY=(`cat hook-log-latest | sed "s/'//g" | grep -m 2 -o 'OPENSHIFT_CAS_NODE_FROM_STORAGE=.*' | cut -d '=' -f 2 | cut -d ':' -f 1`)
CAS_PORT_ARRAY=(`cat hook-log-latest | sed "s/'//g" | grep -m 2 -o 'OPENSHIFT_CAS_NODE_FROM_STORAGE=.*' | cut -d '=' -f 2 | cut -d ':' -f 2`)

CAS_NAME0=(`echo ${CAS_NAME_ARRAY[0]}`)
CAS_PORT0=(`echo ${CAS_PORT_ARRAY[0]}`)

CAS_NAME=(`echo ${CAS_NAME_ARRAY[1]}`)
CAS_PORT=(`echo ${CAS_PORT_ARRAY[1]}`)

echo $CAS_NAME0
echo $CAS_PORT0


echo $CAS_NAME
echo $CAS_PORT

get_cas_ip

echo $CAS_NAME
echo $CAS_IP
echo $CAS_PORT
echo "HERE1"
grep "scaledb_cas_server_ips *=.*$CAS_IP" ${OPENSHIFT_MARIADB_DIR}/cas.cnf
if [ $? -ne 0 ];then
    echo "ip is not in the cas_server_ips list, adding"
    cas_list=`grep "scaledb_cas_server_ips.*" ${OPENSHIFT_MARIADB_DIR}/cas.cnf 2>/dev/null`
    cas_list="$cas_list,$CAS_IP"
    sed -i "s/scaledb_cas_server_ips.*/$cas_list/" ${OPENSHIFT_MARIADB_DIR}/cas.cnf
fi
echo "HERE"

grep "scaledb_cas_server_ips *=.*$CAS_IP" ${OPENSHIFT_MARIADB_DIR}/cas.cnf &>/dev/null
if [ $? -ne 0 ];then
    echo "ERROR - failed to update scaledb_cas_server_ips"
    exit 1
fi

grep "scaledb_cas_server_ports *=.*$CAS_PORT" ${OPENSHIFT_MARIADB_DIR}/cas.cnf &>/dev/null
if [ $? -ne 0 ];then
    echo "port is not in the cas_server_ports list, adding"
    cas_list=`grep "scaledb_cas_server_ports.*" ${OPENSHIFT_MARIADB_DIR}/cas.cnf 2>/dev/null`
    cas_list="$cas_list,$CAS_PORT"
    sed -i "s/scaledb_cas_server_ports.*/$cas_list/" ${OPENSHIFT_MARIADB_DIR}/cas.cnf
fi

grep "scaledb_cas_server_ports *=.*$CAS_PORT" ${OPENSHIFT_MARIADB_DIR}/cas.cnf &>/dev/null
if [ $? -ne 0 ];then
    echo "ERROR - failed to update scaledb_cas_server_ports"
    exit 1
fi








